In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = {"Name":["Zubaer","Rahim","Karim","Salma"],
 "Age":[22,np.nan, 24, np.nan],
 "Salary":[50000,35000,np.nan, 44000],
 "Gender":['M','M',np.nan,'F']

 }

In [7]:
df = pd.DataFrame(dataset)

df

     Name   Age   Salary Gender
0  Zubaer  22.0  50000.0      M
1   Rahim   NaN  35000.0      M
2   Karim  24.0      NaN    NaN
3   Salma   NaN  44000.0      F

# **Missing Value Handling**

In [8]:
df.isnull().sum() #check missing Value

Name      0
Age       2
Salary    1
Gender    1
dtype: int64

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [10]:
df

     Name   Age   Salary Gender
0  Zubaer  22.0  50000.0      M
1   Rahim  23.0  35000.0      M
2   Karim  24.0      NaN    NaN
3   Salma  23.0  44000.0      F

In [11]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [12]:
df

     Name   Age   Salary Gender
0  Zubaer  22.0  50000.0      M
1   Rahim  23.0  35000.0      M
2   Karim  24.0  44000.0    NaN
3   Salma  23.0  44000.0      F

In [15]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [16]:
df

     Name   Age   Salary Gender
0  Zubaer  22.0  50000.0      M
1   Rahim  23.0  35000.0      M
2   Karim  24.0  44000.0      M
3   Salma  23.0  44000.0      F

# **Group Base Analysis**

In [18]:
sales=pd.DataFrame({
  "City":['Dhaka','Khulna',"Dhaka",'Dhaka','Khulna'],
  "Category" :['Laptop','mouse','mouse','Laptop','Laptop'],
  "Sales":[20000,4000,3000,30000,50000]

})

sales

     City Category  Sales
0   Dhaka   Laptop  20000
1  Khulna    mouse   4000
2   Dhaka    mouse   3000
3   Dhaka   Laptop  30000
4  Khulna   Laptop  50000

In [20]:
sales.groupby('Category')['Sales'].mean()

Category
Laptop    33333.333333
mouse      3500.000000
Name: Sales, dtype: float64